trigger: none

resources:
  repositories:
    - repository: PipelineTemplates
      type: git
      name: CDKProjects/PipelineTemplates
pool:
  vmImage: ubuntu-latest
stages:
  - stage: DeployDev
    displayName: Deploy to Dev Environment
    jobs:
    - deployment: DeployDev
      variables:
      - group: SecretsAndConfigDemoEnvironment-Dev
      environment: ssm-parameter-store-webapp-dev
      strategy:
        runOnce:
          deploy:
            steps:    
            - checkout: self
              path: webapp
            - template: build/webappbuild.yml@PipelineTemplates
              parameters:
                EcrRepository: $(EcrRepository)
                BuildId: $(Build.BuildId)
                region: $(AWS.Region)
                AWSCredential: 'AWS-Dotnet-Ohio'             
                DockerFileLocation: $(Agent.BuildDirectory)/webapp/param-web-app/param-web-app/Dockerfile

  - stage: DeployStaging 
    displayName: Deploy to Staging Environment
    jobs:
    - deployment: DeployStg
      variables:
      - group: SecretsAndConfigDemoEnvironment-Stage 
      environment: ssm-parameter-store-webapp-stg
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self              
              path: webapp
            - template: build/webappbuild.yml@PipelineTemplates
              parameters:
                EcrRepository: $(EcrRepository)
                BuildId: $(Build.BuildId)
                region: $(AWS.Region)
                AWSCredential: 'AWS-Dotnet-Ohio'
                DockerFileLocation: $(Agent.BuildDirectory)/webapp/param-web-app/param-web-app/Dockerfile              
  - stage: DeployProduction
    displayName: Deploy to Production Environment
    jobs:
    - deployment: DeployProd
      variables:
      - group: SecretsAndConfigDemoEnvironment-Prod
      environment: ssm-parameter-store-webapp-prod
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
              path: webapp
            - template: build/webappbuild.yml@PipelineTemplates
              parameters:
                EcrRepository: $(EcrRepository)
                BuildId: $(Build.BuildId)
                region: $(AWS.Region)
                AWSCredential: 'AWS-Dotnet-Ohio'  
                DockerFileLocation: $(Agent.BuildDirectory)/webapp/param-web-app/param-web-app/Dockerfile                





