trigger: none

pool:
  vmImage: ubuntu-latest


# variables:
# - group: SecretsAndConfigDemoEnvironment-Stage

stages:
  - stage: DeployDev
    variables:
    - group: SecretsAndConfigDemoEnvironment-Dev 
    jobs:
      - job: DeployDev
        steps:
          - template: build/webappbuild.yml
            parameters:
              EcrRepository: $(EcrRepository)
              BuildId: $(Build.BuildId)
              region: $(AWS.Region)

  - stage: DeployStaging
    displayName: Deploy to Staging Environment
    jobs:
    - deployment: DeployStg
      variables:
      - group: SecretsAndConfigDemoEnvironment-Stage 
      environment: ssm-parameter-store-webapp-stg
      strategy:
        runOnce:
          deploy:
            steps:
            - template: build/webappbuild.yml
              parameters:
                EcrRepository: $(EcrRepository)
                BuildId: $(Build.BuildId)
                region: $(AWS.Region)
# - stage: DeployProduction
#   displayName: Deploy to Production Environment
#   jobs:
#   - deployment: DeployProd
#     variables:
#     - group: SecretsAndConfigDemoEnvironment-Prod
#     environment: ssm-parameter-store-webapp-prod
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - template: build/webappbuild.yml
#             parameters:
#               EcrRepository: $(EcrRepository)
#               BuildId: $(Build.BuildId)
#               region: $(AWS.Region)
  





