trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- group: SecretsAndConfigDemoEnvironment-Stage

resources:
  repositories:
    - repository: PipelineTemplates
      type: git
      name: CDKProjects/PipelineTemplates

stages:
  - stage: DeployDev
    displayName: Deploy Infrastructure to Dev Environment
    jobs:
    - deployment: DeployCdkDev
      variables:
      - group: SecretsAndConfigDemoEnvironment-Dev
      environment: ssm-parameter-store-webapp-dev
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
              path: cdk
            - template: build/cdkdeploy.yml@PipelineTemplates
              parameters:
                Environment: $(Environment)
                EcrRepository: $(EcrRepository)
                Account: $(Account)
                Region: $(AWS.Region)
                StackPrefix: $(StackPrefix)
                WorkingDirectory: $(Agent.BuildDirectory)/cdk
  # - stage: DeployStage
  #   displayName: Deploy Infrastructure to Staging Environment
  #   jobs:
  #   - deployment: DeployCdkStage
  #     variables:
  #     - group: SecretsAndConfigDemoEnvironment-Stage
  #     environment: ssm-parameter-store-webapp-stg
  #     strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #           - checkout: self
  #           - template: build/cdkdeploy.yml
  #             parameters:
  #               Environment: $(Environment)
  #               EcrRepository: $(EcrRepository)
  #               Account: $(Account)
  #               Region: $(AWS.Region)
  #               StackPrefix: $(StackPrefix)
  # - stage: DeployProd
  #   displayName: Deploy Infrastructure to Production Environment
  #   jobs:
  #   - deployment: DeployCdkProd
  #     variables:
  #     - group: SecretsAndConfigDemoEnvironment-Prod
  #     environment: ssm-parameter-store-webapp-prod
  #     strategy:
  #       runOnce:
  #         deploy:
  #           steps:
  #           - checkout: self
  #           - template: build/cdkdeploy.yml
  #             parameters:
  #               Environment: $(Environment)
  #               EcrRepository: $(EcrRepository)
  #               Account: $(Account)
  #               Region: $(AWS.Region)
  #               StackPrefix: $(StackPrefix)
