name: Deploy SSM Parameter Store Demo with AppRunner
on:
  workflow_dispatch:
    inputs:
      env-name:
        type: string
        required: true
        default: dev
      region:
        type: string
        required: true
        default: us-east-1
env:
  REPO_NAME: ${{ inputs.env-name }}-app-repo
  STACK_NAME: ${{ inputs.env-name }}-repo-stack
  ASSUMED_ROLE: arn:aws:iam::654428775930:role/GitHubActionsAssumedRole
  REGION: ${{ inputs.region }}
jobs:
  create-ecr-repo:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3   
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ASSUMED_ROLE }}
          aws-region: ${{ env.REGION }}
      - name: Deploy ECR repo
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          repo-name: $REPO_NAME
          assumed-role: ${{ env.ASSUMED_ROLE }}
          aws-region: ${{ env.REGION }}
          template: ./create-repository-cf/createrepository.yml
          name: ${{ env.STACK_NAME }}
          parameter-overrides: "RepoName=$REPO_NAME"    
          no-fail-on-empty-changeset: "1"
      
