name: DEV-DeployAppRunner
permissions:
  id-token: write
  contents: read
on: 
  workflow_run:
    workflows: [DEV-Deploy .NET Container]
    types: [completed]
jobs:
  deploy-cdk-dev:
    name: Deploy CDK Dev
    uses: ./.github/workflows/deploy-infra.yml
    with:
      environment: Development
