name: Deploy SSM Parameter Store Demo with AppRunner
permissions:
  id-token: write
  contents: read
on: workflow_dispatch
jobs:
  create-ecr-repo-dev:
    name: Create Development Repo
    uses: ./.github/workflows/create-repo.yml
    with:
      environment: Development
  deploy-cdk:
    needs: create-ecr-repo-dev
    name: Deploy CDK
    runs-on: self-hosted
    steps:
      - name: Update CDK
        uses: cbossie-dev/custom-actions/install-cdk@main
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654428775930:role/GitHubActionsAssumedRole
          aws-region: us-east-1
      - run: |
          cdk deploy --require-approval never \
            --context environmentName=dev \
            --context ecrRepository=dev-app-repo \
            --context stackPrefix=DemoInfrastructureStack \
            --context region=us-east-1
  #create-ecr-repo-qa:
  # name: Create QA Repo
  #  uses: ./.github/workflows/create-repo.yml
  #  needs: create-ecr-repo-dev
  #  with:
  #    environment: QA
  #create-ecr-repo-prod:
  #  name: Create Prod Repo
  #  needs: create-ecr-repo-qa
  #  uses: ./.github/workflows/create-repo.yml
  #  with:
  #    environment: Prod        
