name: (SUB)Deploy CDK Stack to a Single Environment
permissions:
  id-token: write
  contents: read
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  deploy-cdk:
    environment: ${{ inputs.environment }}  
    runs-on: self-hosted
    name: Deploy CDK
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update CDK
        uses: cbossie-dev/custom-actions/install-cdk@main        
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ASSUMED_ROLE }}
          aws-region: ${{ vars.REGION }}
      - run: |
          cd demo-infrastructure-cdk
          cdk deploy --require-approval never \
            --context environmentName=${{ vars.APP_ENV }} \
            --context ecrRepository=${{ vars.APP_ENV }}-app-repo \
            --context stackPrefix=${{ vars.STACK_PREFIX }} \
            --context region=${{ vars.REGION }}      
