name: Deploy Containerized .NET APP
permissions:
  id-token: write
  contents: read
on: workflow_dispatch
jobs:
  create-ecr-repo-dev:
    name: Create Development Repo
    uses: ./.github/workflows/create-repo.yml
    with:
      environment: Development
  create-ecr-repo-qa:
   name: Create QA Repo
   uses: ./.github/workflows/create-repo.yml
   needs: deploy-cdk-dev
   with:
     environment: QA
  create-ecr-repo-prod:
    name: Create Prod Repo
    needs: deploy-cdk-qa
    uses: ./.github/workflows/create-repo.yml
    with:
      environment: Prod       
